### ISSUE TITLE
Versions not set on the main page

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image-web#33]
On http://scikit-image.org/, the sidebar shows

```

 Stable (release notes)

x.y.z
Download
Development

pre-x.y.z

```

Desired behavior: x.y.z must be a version number.

**Comment by soupault** [comment]
@sciunto what browser(+extensions) do you have?
The issue was fixed for me with https://github.com/scikit-image/scikit-image-web/pull/32 .

**Comment by sciunto** [comment]
Right. Seems to be caused by one of my extensions. It works with a fresh profile.

**Comment by sciunto** [comment]
I can't find the extension causing this. Anyway... :)
