### ISSUE TITLE
Redirect www.scikit-image.org ?

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image-web#52]
Can it be redirect it to `scikit-image.org` ?

I spent 10 minutes the other day thinking my internet connection was down. 🐴 

XRef: https://github.com/scikit-image/scikit-image/issues/3372

**Comment by sciunto** [comment]
In this case, use https://downforeveryoneorjustme.com/

**Comment by stefanv** [comment]
I set up the redirect; give it 24 hours.

**Comment by stefanv** [comment]
Resolves for me now.
