### ISSUE TITLE
(Possibly) duplicated section in "Installing scikit-image"

### ISSUE THREAD

**Issue by alexandrejaguar** [scikit-image/scikit-image-web#59]
Hey everyone,
I was reinstalling the package today, and checking the _Install_ page, I noticed that [2. Development installation](http://scikit-image.org/docs/dev/install.html#development-installation) has two sections that ask for the same packages: [Build Requirements (docs)](http://scikit-image.org/docs/dev/install.html#build-requirements-docs) and [Documentation requirements](http://scikit-image.org/docs/dev/install.html#documentation-requirements).
Are these two duplicated sections? If not, I wonder if they could be rewritten as one.
Thanks!

**Comment by soupault** [comment]
Good catch! Clearly one of the duplicates can and should be removed.

**Comment by soupault** [comment]
However, the issue is related to the main repository. `scikit-image-web` is dedicated exclusively to the front page of the website.
