### ISSUE TITLE
Is robots.txt uploaded correctly?

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image-web#78]
We disallow old versions of the docs in our robots.txt file, but they still appear in search results, e.g. https://duckduckgo.com/?t=ffab&q=scikit-image+find_contours&ia=web

However, scikit-image.org/robots.txt currently returns a 404, so I'm wondering whether we inadvertently stopped sharing that on gh-pages at some point.

CC @stefanv 

Context: https://github.com/scikit-image/scikit-image/issues/6020

**Comment by stefanv** [comment]
Closed via https://github.com/scikit-image/scikit-image-web/commit/0885971076438371e7aefc4a6e23f7def84629ce
